/**
 * DO NOT EDIT THIS FILE DIRECTLY
 * Head over to utils/shopify.js to create your events
 *  and write your event functions in utils/events.
 * To update this file, run `npm run update:config` or `bun run update:config`
 */

import shopify from "../../utils/shopify.js";

const eventHandler = async (req, res) => {
  const topic = req.headers["shopify-topic"] || "";
  const shop = req.headers["shopify-shop-domain"] || "";
  const apiVersion = req.headers["shopify-api-version"] || "";
  const handle = req.headers["shopify-handle"] || "";
  const webhookId = req.headers["shopify-webhook-id"] || "";

  try {
    const validateEvent = await shopify.webhooks.validate({
      rawBody: req.body,
      rawRequest: req,
      rawResponse: res,
    });

    if (validateEvent.valid) {
    } else {
      return res.status(400).send({ error: true });
    }

    const eventHandle = validateEvent.handle || handle;

    //SWITCHCASE
    switch (eventHandle) {
      default:
        throw new Error(`Can't find a handler for ${eventHandle}`);
    }
    //SWITCHCASE END
    console.log(`--> Processed ${topic} webhook for ${shop}`);
    return res.status(200).send({ message: "ok" });
  } catch (e) {
    console.error(
      `---> Error while registering ${topic} webhook for ${shop}`,
      e
    );
    if (!res.headersSent) {
      return res.status(500).send(e.message);
    }
  }
};

export default eventHandler;
