/**
 * DO NOT EDIT THIS FILE DIRECTLY
 * Head over to utils/shopify.js to create your events
 *  and write your event functions in utils/events.
 * To update this file, run `npm run update:config` or `bun run update:config`
 */

const eventHandler = async (req, res) => {
  const { shop } = res.locals.shop_context;
  const topic = req.headers["shopify-topic"] || "";
  const apiVersion = req.headers["shopify-api-version"] || "";
  const handle = req.headers["shopify-handle"] || "";
  const webhookId = req.headers["shopify-webhook-id"] || "";

  try {
    //SWITCHCASE
    switch (handle) {
      default:
        throw new Error(`Can't find a handler for ${handle}`);
    }
    //SWITCHCASE END
    console.log(`--> Processed ${topic} webhook for ${shop}`);
    return res.status(200).send({ message: "ok" });
  } catch (e) {
    console.error(
      `---> Error while registering ${topic} webhook for ${shop}`,
      e
    );
    if (!res.headersSent) {
      return res.status(500).send(e.message);
    }
  }
};

export default eventHandler;
